In [11]:
from tensorflow.keras.preprocessing.text import one_hot

In [12]:
sent = ['the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'I am a good developer',
        'understand the meaning of words',
        'your videos are good']
        

In [13]:
voc_size = 10000

In [14]:
one_hot_repr = [one_hot(words, voc_size) for words in sent]

In [15]:
one_hot_repr

[[1552, 5612, 876, 5946],
 [1552, 5612, 876, 6919],
 [1552, 290, 876, 9710],
 [8485, 8463, 3372, 3174, 541],
 [8485, 8463, 3372, 3174, 3748],
 [6252, 1552, 4895, 876, 1834],
 [3746, 6499, 2916, 3174]]

In [18]:
from tensorflow.keras.layers import Embedding 
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [19]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen = sent_length)

In [20]:
embedded_docs

array([[   0,    0,    0,    0, 1552, 5612,  876, 5946],
       [   0,    0,    0,    0, 1552, 5612,  876, 6919],
       [   0,    0,    0,    0, 1552,  290,  876, 9710],
       [   0,    0,    0, 8485, 8463, 3372, 3174,  541],
       [   0,    0,    0, 8485, 8463, 3372, 3174, 3748],
       [   0,    0,    0, 6252, 1552, 4895,  876, 1834],
       [   0,    0,    0,    0, 3746, 6499, 2916, 3174]], dtype=int32)

In [21]:
dim = 10
model = Sequential()
model.add(Embedding(voc_size, dim, input_length = sent_length))
model.compile('adam','mse')

c:\Users\Varun Gaming\End To End Projects\Deep Learning NLP\venv\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [22]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [23]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 203ms/step


array([[[-0.01955221,  0.04820161, -0.01092963, -0.0258499 ,
          0.02524947, -0.01456083, -0.02209772, -0.03773163,
          0.04054886, -0.04030429],
        [-0.01955221,  0.04820161, -0.01092963, -0.0258499 ,
          0.02524947, -0.01456083, -0.02209772, -0.03773163,
          0.04054886, -0.04030429],
        [-0.01955221,  0.04820161, -0.01092963, -0.0258499 ,
          0.02524947, -0.01456083, -0.02209772, -0.03773163,
          0.04054886, -0.04030429],
        [-0.01955221,  0.04820161, -0.01092963, -0.0258499 ,
          0.02524947, -0.01456083, -0.02209772, -0.03773163,
          0.04054886, -0.04030429],
        [ 0.02024772,  0.03685998,  0.02639839,  0.04965306,
         -0.00659273,  0.02398233, -0.01424187,  0.01270894,
         -0.03331967, -0.02926855],
        [-0.00326033,  0.04407647, -0.01184585, -0.02524979,
         -0.00751694,  0.0126051 , -0.03080251,  0.00060142,
         -0.03394095,  0.03264339],
        [-0.04652005,  0.01056342,  0.03207929, -0.0

In [24]:
embedded_docs[0]

array([   0,    0,    0,    0, 1552, 5612,  876, 5946], dtype=int32)